#!/bin/bash

OPS=$(echo "${@:1}" | tr -d " " | sed s/--/_/g)
mkdir -p ./out

echo "Comparing scenario ${@:1}" 

FILENAME="scenario${OPS}"
./simulate "${@:1} --legacy" > ./out/${FILENAME}_legacy.txt
./simulate "${@:1}" > ./out/${FILENAME}_proposal.txt

./plot-success ./out/${FILENAME} > ./out/success_${OPS}.png
./plot-exposure ./out/${FILENAME} > ./out/exposure_${OPS}.png
./plot-time-to-success ./out/${FILENAME} > ./out/time-to-success_${OPS}.png

