#!/bin/bash

SCENARIO="$1"

SCRIPT="
stats '${SCENARIO}_legacy.txt' using 3;
min_y = STATS_min;

stats '${SCENARIO}_proposal.txt' using 3;
min_y = min_y < STATS_min ? min_y : STATS_min;

show variable all;

set terminal png size 700,300;

unset xtics;
set yrange [min_y:100];
set key off;
set style fill solid;

set multiplot layout 1,2 columnsfirst title \"{/:Bold=15 Success rate (%)}\";

set title \"Original Algorithm\";
plot '${SCENARIO}_legacy.txt' using 3 with boxes;

set title \"Proposal\";
plot '${SCENARIO}_proposal.txt' using 3 with boxes;

unset multiplot;
"

gnuplot -p -e "$SCRIPT"

