#!/bin/bash

TIMES=100

echo "i success total success-rate capacity 1 15 30 exposure-1 exposure-15 exposure-30 guards-till-first-circuit time-till-first-circuit time-first-success total-time"

for i in `seq 1 $TIMES`;
do
  echo -n "$i "
  echo $(./lib/main.py ${@:1} | tail -n 8 | grep -E "[0-9.]+" -o | xargs)
done

