#!/bin/bash

set -xe

# vanilla
./plot -L
./plot

# Fascist network
./plot -F -L
./plot -F

# Flaky
./plot -f -L
./plot -f

# Evil
./plot -e -L
./plot -e

# Sniper
./plot -s -L
./plot -s

# switch between networks
./plot -S -L
./plot -S

