#!/bin/bash

set -xe

# vanilla
./plot --legacy
./plot

# Fascist network
./plot --fascist-firewall --legacy
./plot --fascist-firewall

# Flaky
./plot --flaky-network --legacy
./plot --flaky-network

# Evil
./plot --evil-filtering --legacy
./plot --evil-filtering

# Sniper
./plot --sniper-network --legacy
./plot --sniper-network

# switch between networks
./plot --switching-network --legacy
./plot --switching-network

